#include <iostream>
#include <map>
#include <algorithm>
#include <vector>
#include <stack>
#include <set>
#include <unordered_set>
#include <utility>
#include <numeric>
#include <sstream>
#include <ranges>
#include <math.h>
#include <util.h>
#include <semaphore.h>
#include <tuple>
#include <queue>